routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use JeroenNoten\LaravelAdminLte\Components\Form\Select;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');*/

Route::get('socios/{id}/pdf', [App\Http\Controllers\SocioController::class, 'pdf'] )->name('socios.pdf');



Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
    
    //Route::get('/socios',Socios::class);
    Route::resource('socios','App\Http\Controllers\SocioController');
    Route::resource('personas','App\Http\Controllers\PersonaController');
    Route::resource('maquinarias','App\Http\Controllers\MaquinariaController');
    Route::resource('asistencias','App\Http\Controllers\AsistenciaController');

    Route::view('selects','selects');

    Route::get('/socios/provinciasByDep/{id}','App\Http\Controllers\SocioController@provinciasByDep');
    Route::get('/socios/distritosByProv/{id}','App\Http\Controllers\SocioController@distritosByProv');

    

app/Models/Persona.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Persona extends Model
{
    use HasFactory;
    protected $fillable = ['nombre', 'ape_paterno', 'ape_materno', 'dni', 'dni', 'fe_nacimiento', 'es_civil', 'sexo', 'telefono', 'email', 'direccion', 'es_persona', 'fa_parentesco', 'parentesco'];

    public function socio() {
        return $this->hasOne('App\Models\Socio');
    }
}

app/Http/Controllers/PersonaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Persona;

class PersonaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $personas=Persona::all();
        return view('personas.list', compact( 'personas'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('personas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'nombre' => 'required',
            'ape_paterno' => 'required',
            'ape_materno' => 'required',
            'dni' => 'required',
            'fe_nacimiento' => 'required',
            'es_civil' => 'required',
            'sexo' => 'required',
            'telefono' => 'required',
            'email' => 'required',
            'direccion' => 'required',
            'es_persona' => 'required',
            'fa_parentesco',
            'parentesco',

        ]);

        $persona = new Persona();
        $persona->nombre = $request->get('nombre');
        $persona->ape_paterno = $request->get('ape_paterno');
        $persona->ape_materno = $request->get('ape_materno');
        $persona->dni = $request->get('dni');
        $persona->fe_nacimiento = $request->get('fe_nacimiento');
        $persona->es_civil = $request->get('es_civil');
        $persona->sexo = $request->get('sexo');
        $persona->telefono = $request->get('telefono');
        $persona->email = $request->get('email');
        $persona->direccion = $request->get('direccion');
        $persona->es_persona = $request->get('es_persona');
        $persona->fa_parentesco = $request->get('fa_parentesco');
        $persona->parentesco = $request->get('parentesco');

        $persona->save();

        return redirect('/personas');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $personas=Persona::find($id);
        return view('personas.edit', compact( 'personas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'nombre' => 'required',
            'ape_paterno' => 'required',
            'ape_materno' => 'required',
            'dni' => 'required',
            'fe_nacimiento' => 'required',
            'es_civil' => 'required',
            'sexo' => 'required',
            'telefono' => 'required',
            'email' => 'required',
            'direccion' => 'required',
            'es_persona' => 'required',
            'fa_parentesco',
            'parentesco',

        ]);

        $persona = Persona::find($id);
        $persona->nombre = $request->get('nombre');
        $persona->ape_paterno = $request->get('ape_paterno');
        $persona->ape_materno = $request->get('ape_materno');
        $persona->dni = $request->get('dni');
        $persona->fe_nacimiento = $request->get('fe_nacimiento');
        $persona->es_civil = $request->get('es_civil');
        $persona->sexo = $request->get('sexo');
        $persona->telefono = $request->get('telefono');
        $persona->email = $request->get('email');
        $persona->direccion = $request->get('direccion');
        $persona->es_persona = $request->get('es_persona');
        $persona->fa_parentesco = $request->get('fa_parentesco');
        $persona->parentesco = $request->get('parentesco');

        $persona->save();

        return redirect('/personas');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $persona = Persona::find($id);
        $persona->delete();
        return redirect('/personas');
    }
}

resources/views/personas/create.blade.php
@extends('adminlte::page')

@section('title', 'Persona')

@section('content_header')
    <h1>Persona</h1>
@stop

@section('content')

    <p> REGISTRO DE PERSONAS.</p>

    <form action="/personas" method="POST">
        @csrf
        <div class="container">
          <div class="row">
            <div class="form-group col">
                <label>Nombres</label>
                <input type="text" name="nombre" id="nombre" class="form-control form-control-border border-width-2 @error('nombre') is-invalid @enderror" wire:model="nombre">
                @error('nombre')
                <small class="form-text text-danger">{{$message}}</small>
                @enderror
            </div>
            <div class="form-group col">
                <label>Apellido Paterno</label>
                <input type="text" name="ape_paterno" id="ape_paterno"  wire:model="ape_paterno" 
                  class="form-control form-control-border border-width-2 @error('ape_paterno') is-invalid @enderror">
                @error('ape_paterno')
                <small class="form-text text-danger">{{$message}}</small>
                @enderror
            </div>
            <div class="form-group col">
                <label>Apellido Materno</label>
                <input type="text" name="ape_materno" id="ape_materno"  wire:model="ape_materno" 
                  class="form-control form-control-border border-width-2 @error('ape_materno') is-invalid @enderror">
                @error('ape_materno')
                <small class="form-text text-danger">{{$message}}</small>
                @enderror
            </div>
          </div>
          <div class="row">
          <div class="form-group col-md-3">
            <label class="form-label">DNI</label>
            <input name="dni" id="dni" type="number" class="form-control" wire:model="dni">
            </div>
            <div class="form-group col-md-3">
            <label class="form-label">Fecha Nacimiento</label>
            <input name="fe_nacimiento" id="fe_nacimiento" type="date" class="form-control" wire:model="fe_nacimiento">
            </div>
            <div class="form-group col-md-3">
              <label for="inputState">Estado Civil</label>
              <select id="es_civil" class="form-control" name="es_civil" wire:model="es_civil">
                <option selected>Eligue una Opcion</option>
                <option value="1">Soltero</option>
                <option value="2">Casado</option>
                <option value="3">Divorciado</option>
                <option value="4">Viudo</option>
              </select>
            </div>
            <div class="form-group col-md-3">
            <label class="form-label">Sexo</label>
            <select id="sexo" class="form-control" name="sexo" wire:model="sexo">
                <option selected>Eligue una Opcion</option>
                <option value="1">Masculino</option>
                <option value="2">Femenino</option>
              </select>
            </div>
          </div>
          <div class="row">
            <div class="mb-3 col">
                <label class="form-label">Telefono</label>
                <input name="telefono" name="telefono" type="text" class="form-control" wire:model="telefono">
            </div>
            <div class="mb-3 col">
                <label class="form-label">Correo Electronico</label>
                <input name="email" id="email" type="email" class="form-control" wire:model="email">
            </div>
            <div class="mb-3 col">
                <label class="form-label">Direccion</label>
                <input name="direccion" id="direccion" type="text" class="form-control" wire:model="direccion">
            </div>
            <div class="mb-3 col invisible">
                <label class="form-label">Estado</label>
                <input name="es_persona" id="es_persona" type="text" class="form-control" wire:model="es_persona" value="1">
            </div>
          </div>
          <div class="row">
            <div class="mb-3 col">
                <label class="form-label">Familia</label>
                <input name="fa_parentesco" id="fa_parentesco" type="text" class="form-control" wire:model="fa_parentesco">
            </div>
            <div class="mb-3 col">
                <label class="form-label">Parentesco</label>
                <input name="parentesco" id="parentesco" type="text" class="form-control" wire:model="parentesco">
            </div>
          </div>
  </div>
<div class="float-end">
            <a href="/personas" class="me-2 btn btn-danger">Cerrar</a>
            <button  type="submit" class="btn btn-success">Guardar</button>
        </div>
    </form>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/personas/edit.blade.php
@extends('adminlte::page')

@section('title', 'Persona')

@section('content_header')
    <h1>Persona</h1>
@stop

@section('content')

    <p> REGISTRO DE PERSONAS.</p>

    <form action="/personas/{{$personas->id}}" method="POST">
        @csrf
        @method('PUT')
        <div class="container">
  <div class="row">
    <div class="mb-3 col">
    <label class="form-label">Nombre</label>
    <input name="nombre" id="nombre" type="text" class="form-control" wire:model="nombre" value="{{$personas->nombre}}">
    </div>
    <div class="mb-3 col">
    <label class="form-label">Apellido Paterno</label>
    <input name="ape_paterno" id="ape_paterno" type="text" class="form-control" wire:model="ape_paterno" value="{{$personas->ape_paterno}}">
    </div>
    <div class="mb-3 col">
    <label class="form-label">Apellido Materno</label>
    <input name="ape_materno" id="ape_materno" type="text" class="form-control" wire:model="ape_materno" value="{{$personas->ape_materno}}">
    </div>
  </div>
  <div class="row">
  <div class="form-group col-md-3">
    <label class="form-label">DNI</label>
    <input name="dni" id="dni" type="number" class="form-control" wire:model="dni" value="{{$personas->dni}}">
    </div>
    <div class="form-group col-md-3">
    <label class="form-label">Fecha Nacimiento</label>
    <input name="fe_nacimiento" id="fe_nacimiento" type="date" class="form-control" wire:model="fe_nacimiento" value="{{$personas->fe_nacimiento}}">
    </div>
    <div class="form-group col-md-3">
      <label for="inputState">Estado Civil</label>
      <select id="es_civil" class="form-control" name="es_civil" wire:model="es_civil">
      @if (!$personas)
          <option value="" selected disabled>Eligue una Opcion</option>
          @else
            <option value="1" @if($personas->es_civil == '1') selected
              @endif>Soltero</option>
            <option value="2" @if($personas->es_civil == '2') selected
              @endif>Casado</option>
              <option value="3" @if($personas->es_civil == '3') selected
              @endif>Divorciado</option>
              <option value="4" @if($personas->es_civil == '4') selected
              @endif>Viudo</option>
        @endif
      </select>
    </div>
    <div class="form-group col-md-3">
    <label class="form-label">Sexo</label>
    <select id="sexo" class="form-control" name="sexo" wire:model="sexo">
      @if (!$personas)
        <option value="" selected disabled>Eligue una Opcion</option>
        @else
        <option value="1" @if($personas->sexo == '1') selected
              @endif>Masculino</option>
        <option value="2" @if($personas->sexo == '2') selected
              @endif>Femenino</option>
        @endif
      </select>
    </div>
  </div>
  <div class="row">
    <div class="mb-3 col">
        <label class="form-label">Telefono</label>
        <input name="telefono" name="telefono" type="text" class="form-control" wire:model="telefono" value="{{$personas->telefono}}">
    </div>
    <div class="mb-3 col">
        <label class="form-label">Correo Electronico</label>
        <input name="email" id="email" type="email" class="form-control" wire:model="email" value="{{$personas->email}}">
    </div>
    <div class="mb-3 col">
        <label class="form-label">Direccion</label>
        <input name="direccion" id="direccion" type="text" class="form-control" wire:model="direccion" value="{{$personas->direccion}}">
    </div>
    <div class="mb-3 col invisible">
        <label class="form-label">Estado</label>
        <input name="es_persona" id="es_persona" type="text" class="form-control" wire:model="es_persona" value="{{$personas->es_persona}}">
    </div>
  </div>
  <div class="row">
    <div class="mb-3 col">
        <label class="form-label">Familia</label>
        <input name="fa_parentesco" id="fa_parentesco" type="text" class="form-control" wire:model="fa_parentesco" value="{{$personas->fa_parentesco}}" >
    </div>
    <div class="mb-3 col">
        <label class="form-label">Parentesco</label>
        <input name="parentesco" id="parentesco" type="text" class="form-control" wire:model="parentesco" value="{{$personas->parentesco}}">
    </div>
  </div>
</div>
<div class="float-end">
            <a href="/personas" class="me-2 btn btn-danger">Cerrar</a>
            <button  type="submit" class="btn btn-success">Actaulizar</button>
        </div>
    </form>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/personas/list.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')

    <p> REGISTRO DE PERSONAS.</p>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">DataTable with minimal features & hover style</h3>
                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <div class="input-group-append">
                    <a href="personas/create" class="btn btn-success">Agregar Persona</a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Nombres y apellido</th>
                    <th>Fec. Nacimiento</th>
                    <th>Direccion</th>
                    <th>DNI</th>
                    <th>Acciones</th>
                  </tr>
                  </thead>
                  <tbody>
                      @foreach($personas as $item)
                    <tr>
                      <td>{{$item->id}}</td>
                      <td>{{$item->nombre}}, {{$item->ape_paterno}} {{$item->ape_materno}}</td>
                      <td>{{$item->fe_nacimiento}}</td>
                      <td>{{$item->direccion}}</td>
                      <td>{{$item->dni}}</td>
                      <td>
                        <a class="btn btn-warning" href="/personas/{{$item->id}}/edit">Editar</a>
                        <form action="{{route('personas.destroy', $item->id)}}" method="POST" class="formEliminar">
                            @csrf
                            @method('DELETE')
                            <button type="submit"  class="btn btn-danger">Eliminar</button>
                        </form>
                    </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <div class="card">
              <div class="card-header">
                <h3 class="card-title">DataTable with default features</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                  <th>ID</th>
                    <th>Nombres y apellido</th>
                    <th>Fec. Nacimiento</th>
                    <th>Direccion</th>
                    <th>DNI</th>
                  </tr>
                  </thead>
                  <tbody>
                  @foreach($personas as $item)
                    <tr>
                      <td>{{$item->id}}</td>
                      <td>{{$item->nombre}}, {{$item->ape_paterno}} {{$item->ape_materno}}</td>
                      <td>{{$item->fe_nacimiento}}</td>
                      <td>{{$item->direccion}}</td>
                      <td>{{$item->dni}}</td>
                    </tr>
                    @endforeach
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
@stop

@section('css')
    <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

@stop

@section('js')
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script> console.log('Hi!'); </script>

<script>
  (function () {
    'use strict'

    var forms = document.querySelectorAll('.formEliminar')
    Array.prototype.slice.call(forms)
      .forEach(function (form) {
        form.addEventListener('submit', function (event) {
          event.preventDefault()
          event.stopPropagation()
          Swal.fire({
              title: '¿Desea eliminar al socio?',
              icon: 'info',
              showCancelButton: true,
              confirmButtonColor: '#20c997',
              cancelButtonColor: '#6c757d',
              confirmButtonText: 'Confirmar',
          }).then((result) => {
            if (result.isConfirmed) {
              this.submit();
              Swal.fire('Eliminado', 'El socio se elimino corectamente.','success');
            }
          })
        }, false)            
      });
  })()
</script>

<!-- DataTables  & Plugins -->
<script src="/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="/plugins/jszip/jszip.min.js"></script>
<script src="/plugins/pdfmake/pdfmake.min.js"></script>
<script src="/plugins/pdfmake/vfs_fonts.js"></script>
<script src="/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
@stop