routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use JeroenNoten\LaravelAdminLte\Components\Form\Select;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');*/

Route::get('socios/{id}/pdf', [App\Http\Controllers\SocioController::class, 'pdf'] )->name('socios.pdf');



Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
    
    //Route::get('/socios',Socios::class);
    Route::resource('socios','App\Http\Controllers\SocioController');
    Route::resource('personas','App\Http\Controllers\PersonaController');
    Route::resource('maquinarias','App\Http\Controllers\MaquinariaController');
    Route::resource('asistencias','App\Http\Controllers\AsistenciaController');

    Route::view('selects','selects');

    Route::get('/socios/provinciasByDep/{id}','App\Http\Controllers\SocioController@provinciasByDep');
    Route::get('/socios/distritosByProv/{id}','App\Http\Controllers\SocioController@distritosByProv');

    

app/Models/Asistencia.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Asistencia extends Model
{
    use HasFactory;
    protected $fillable = ['personas_id', 'eventos', 'descripcion','fech_even','estado' ];

    public function persona() {
        return $this->belongsTo(Persona::class, 'personas_id', 'id');
    }
}

app/Http/Controllers/AsistenciaController.php
<?php

namespace App\Http\Controllers;
use App\Models\Persona;
use App\Models\Asistencia;

use Illuminate\Http\Request;

class AsistenciaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $asistencias = Asistencia::all();
        return view('asistencias.list', compact( 'asistencias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $personas = persona::all();
        
        return view('asistencias.create', compact('personas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $asistencias = Asistencia::all();
        $personas = persona::all();

        $request->validate([
            'personas_id' => 'required',
            'eventos' => 'required',
            'descripcion' => 'required',
            'fech_even' => 'required',
            'estado' => 'required'
        ]);
        $asistencias = $request->all();


        Asistencia::create($asistencias);
        return redirect('/asistencias');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $personas = Persona::all();
        $asistencias=Asistencia::find($id);
        return view('asistencias.edit', compact('asistencias','personas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'personas_id' => 'required',
            'eventos' => 'required',
            'descripcion' => 'required',
            'fech_even' => 'required',
            'estado' => 'required',
            
            
        ]);
        $asistencias = $request->all();
        

        return redirect('/asistencias');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $asistencias = Asistencia::find($id);
        $asistencias->delete();
        return redirect('/asistencias');
    }
}

resources/views/asistencias/create.blade.php
@extends('adminlte::page')

@section('title', 'asistencias')

@section('content_header')
    <h1>Asistencias</h1>
@stop

@section('content')
    <form action="/asistencias" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="container">
            
            <div class="row">
                <div class="col-8 form-group">
                    <div class="row form-group">
                        <div class="form-group col">
                            <label>Nombre del Socio
                                <code>*</code></label>
                            <select 
                                class="custom-select form-control-border border-width-2 @error('personas_id') is-invalid @enderror"
                                id="personas_id" name="personas_id" wire:model='personas_id'>
                                <option selected >Seleccionar...</option>
                                    @foreach($personas as $persona)
                                <option value="{{ $persona->id }}">{{ $persona->nombre }}</option>
                                @endforeach
                            </select>
                            @error('personas_id')
                            <small class="form-text text-danger">{{$message}}</small>
                            @enderror
                        </div>
                        <div class="form-group col">
                            <label>eventos
                                <code>*</code></label>
                            <input type="text"
                                class="form-control form-control-border border-width-2 @error('eventos') is-invalid @enderror"
                                id="eventos" name="eventos" wire:model="eventos" placeholder="">
                            @error('eventos')
                            <small class="form-text text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="form-group col">
                            <label>descripcion
                                <code>*</code></label>
                            <input type="text"
                                class="form-control form-control-border border-width-2 @error('descripcion') is-invalid @enderror"
                                id="descripcion" name="descripcion" wire:model="descripcion" placeholder="">
                            @error('tipo')
                            <small class="form-text text-danger">{{$message}}</small>
                            @enderror
                        </div>
                        <div class="form-group col">
                        <label class="form-label">Fecha </label>
            <input name="fech_even" id="fech_even" type="date" class="form-control" wire:model="fech_even">
                        </div>
                        <div class="form-group col">
                        <label class="form-label">estado</label>
                        <select id="estado" class="form-control" name="estado" wire:model="estado">
                <option selected>Eligue una Opcion</option>
                <option value="1">asistio</option>
                <option value="2">inasistio</option>
                
              </select>
                        </div>
                    </div>
                        
              
                
        </div>
        <div class="float-end">
            <a href="/asistencias" class="me-2 btn btn-danger">Cerrar</a>
            <button  type="submit" class="btn btn-success">Guardar</button>
        </div>
    </form>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">    
@stop

@section('js')
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> 
<script>   
    $(document).ready(function (e) {   
        $('#imagen').change(function(){            
            let reader = new FileReader();
            reader.onload = (e) => { 
                $('#imagenSeleccionada').attr('src', e.target.result); 
            }
            reader.readAsDataURL(this.files[0]); 
        });
    });
</script>


<script>
  $(document).ready(function () {
      $('#personas_id').on('change', function (e) {
          var id_dep = $('#personas_id').val();
          console.log(id_dep);
          $.get('personasByDep/'+id_dep, function(data){
            console.log(data);
            $('#apellidos').empty();
            $.each(data, function(fetch,obj){
              $('#personas_id').append('<option value="'+ obj.id +'">'+ obj.ape_paterno + obj.ape_materno +'</option>');
            })
          });
      });
  });
</script>




<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
 
</script>


@stop

resources/views/asistencias/edit.blade.php
@extends('adminlte::page')

@section('title', 'Persona')

@section('content_header')
    <h1>asistencias</h1>
@stop

@section('content')

    <p> REGISTRO DE asistencias.</p>

    <form action="/asistencias/{{$asistencias->id}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="container">
            <div class="row">
                <div class="col-8 form-group">
                    <div class="row form-group">
                        <div class="col">
                        <label>Nombre del Socio
                                <code>*</code></label>
                            <select 
                            class="custom-select form-control-border border-width-2 @error('personas_id') is-invalid @enderror"
                                name="personas_id" id="personas_id" wire:model='personas_id'>
                            @if (!$asistencias->persona)
                                <option value="" selected disabled>Selecciona una Persona</option>
                            @foreach ($personas as $persona)
                                <option value="{{ $persona->id }}">
                                {{ $persona->nombre }}</option>
                            @endforeach
                            @else
                            @foreach ($personas as $persona)
                                <option value="{{ $persona->id }}" @if($asistencias->persona->id === $persona->id)
                            selected='selected'
                            @endif>
                                {{ $persona->nombre }}</option>
                            @endforeach
                            @endif
                            </select>
                            @error('personas_id')
                            <small class="form-text text-danger">{{$message}}</small>
                            @enderror
                        </div>
                        <div class="form-group col">
                        <label>evento
                                <code>*</code></label>
                            <input 
                                class="form-control form-control-border border-width-2 @error('eventos') is-invalid @enderror"
                                id="eventos" name="eventos" wire:model="eventos" placeholder="" value="{{$asistencias->eventos}}">
                            @error('Eventos')
                            <small class="form-text text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="form-group col">
                            <label>descripcion
                                <code>*</code></label>
                            <input type="text"
                                class="form-control form-control-border border-width-2 @error('descripcion') is-invalid @enderror"
                                id="descripcion" name="descripcion" wire:model="descripcion" placeholder="" value="{{$asistencias->descripcion}}">
                            @error('descripcion')
                            <small class="form-text text-danger">{{$message}}</small>
                            @enderror
                        </div>
                        <div class="form-group col">
                        <label class="form-label">Fecha</label>
    <input name="fech_even" id="fech_even" type="date" class="form-control" wire:model="fech_even" value="{{$asistencias->fech_even}}">
                        </div>
                        <div class="form-group col-md-3">
    <label class="form-label">estado</label>
    <select id="estado" class="form-control" name="estado" wire:model="estado">
      @if (!$asistencias)
        <option value="" selected disabled>Eligue una Opcion</option>
        @else
        <option value="1" @if($asistencias->estado == '1') selected
              @endif>asistio</option>
        <option value="2" @if($asistencias->estado == '2') selected
              @endif>inasistio</option>
        @endif
      </select>
    </div>
    </div>
    </div>
                 
              
<div class="float-end">
            <a href="/asistencias" class="me-2 btn btn-danger">Cerrar</a>
            <button  type="submit" class="btn btn-success">Actualizar</button>
        </div>
    </form>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">    
@stop


@section('js')
    <script> console.log('Hi!'); </script>
@stop

 

resources/views/asistencias/list.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')

    <p> REGISTRO DE ASISTENCIAS.</p>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">DataTable with minimal features & hover style</h3>
                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <div class="input-group-append">
                    <a href="asistencias/create" class="btn btn-success">Agregar Asistencias</a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                  <th>ID</th>
                    <th>Eventos</th>
                    <th>descripcion</th>
                    <th>fech_even</th>
                    <th>estado</th>
                    <th>Acciones</th>
                    
                  </tr>
                  </thead>
                  <tbody>
                      @foreach($asistencias as $asistencia)
                        <tr>
                        <td>{{$asistencia->id}}</td>
                        @if ($asistencia->personas_id)
                      <td>{{$asistencia->persona->nombre}} , {{$asistencia->persona->ape_paterno}} {{$asistencia->persona->ape_materno}}</td>
                      @else
                      <td>Desconocido</td>
                      @endif
                        
                      <td>{{$asistencia->eventos}}</td>
                      <td>{{$asistencia->fech_even}}</td>
                      <td>{{$asistencia->estado}}</td>
                      <td width="100px"><!-- width="50px" --> 
                        <div class="d-flex justify-content-center">
                        <a class="btn btn-warning mx-2" href="/asistencias/{{$asistencia->id}}/edit">Editar</a>
                        <form action="{{route('asistencias.destroy', $asistencia->id)}}" method="POST" class="formEliminar">
                            @csrf
                            @method('DELETE')
                            <button type="submit"  class="btn btn-danger">Eliminar</button>
                        </form>
                        </div>
                        
                    </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
            @stop
            

@section('css')
    <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

@stop

@section('js')

<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
  (function () {
    'use strict'

    var forms = document.querySelectorAll('.formEliminar')
    Array.prototype.slice.call(forms)
      .forEach(function (form) {
        form.addEventListener('submit', function (event) {
          event.preventDefault()
          event.stopPropagation()
          Swal.fire({
              title: '¿Desea eliminar la asisterncia?',
              icon: 'info',
              showCancelButton: true,
              confirmButtonColor: '#20c997',
              cancelButtonColor: '#6c757d',
              confirmButtonText: 'Confirmar',
          }).then((result) => {
            if (result.isConfirmed) {
              this.submit();
              Swal.fire('Eliminado', 'La asistencia se elimino corectamente.','success');
            }
          })
        }, false)            
      });
  })()
</script>

    <!-- DataTables  & Plugins -->
<!-- DataTables  & Plugins -->
<script src="/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="/plugins/jszip/jszip.min.js"></script>
<script src="/plugins/pdfmake/pdfmake.min.js"></script>
<script src="/plugins/pdfmake/vfs_fonts.js"></script>
<script src="/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
@stop