routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use JeroenNoten\LaravelAdminLte\Components\Form\Select;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');*/

Route::get('socios/{id}/pdf', [App\Http\Controllers\SocioController::class, 'pdf'] )->name('socios.pdf');



Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
    
    //Route::get('/socios',Socios::class);
    Route::resource('socios','App\Http\Controllers\SocioController');
    Route::resource('personas','App\Http\Controllers\PersonaController');
    Route::resource('maquinarias','App\Http\Controllers\MaquinariaController');
    Route::resource('asistencias','App\Http\Controllers\AsistenciaController');

    Route::view('selects','selects');

    Route::get('/socios/provinciasByDep/{id}','App\Http\Controllers\SocioController@provinciasByDep');
    Route::get('/socios/distritosByProv/{id}','App\Http\Controllers\SocioController@distritosByProv');

    

app/Models/Maquinaria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Maquinaria extends Model
{
    use HasFactory;
}

app/Http/Controllers/MaquinariaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Maquinaria;

class MaquinariaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $maquinarias=Maquinaria::all();
        return view('maquinarias.list', compact( 'maquinarias'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('maquinarias.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'nombre' => 'required',
            'codigo' => 'required',
            'modelo' => 'required',
            'potencia' => 'required',
            'velocidad' => 'required',
            'es_maquinaria' => 'required',
        ]);

        $maquinaria = new Maquinaria();
        $maquinaria->nombre = $request->get('nombre');
        $maquinaria->codigo = $request->get('codigo');
        $maquinaria->modelo = $request->get('modelo');
        $maquinaria->potencia = $request->get('potencia');
        $maquinaria->velocidad = $request->get('velocidad');
        $maquinaria->es_maquinaria = $request->get('es_maquinaria');

        $maquinaria->save();

        return redirect('/maquinarias');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $maquinarias=Maquinaria::find($id);
        return view('maquinarias.edit', compact( 'maquinarias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'nombre' => 'required',
            'codigo' => 'required',
            'modelo' => 'required',
            'potencia' => 'required',
            'velocidad' => 'required',
            'es_maquinaria' => 'required',

        ]);

        $maquinaria = Maquinaria::find($id);
        $maquinaria->nombre = $request->get('nombre');
        $maquinaria->codigo = $request->get('codigo');
        $maquinaria->modelo = $request->get('modelo');
        $maquinaria->potencia = $request->get('potencia');
        $maquinaria->velocidad = $request->get('velocidad');
        $maquinaria->es_maquinaria = $request->get('es_maquinaria');

        $maquinaria->save();

        return redirect('/maquinarias');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $persona = Maquinaria::find($id);
        $persona->delete();
        return redirect('/maquinarias');
    }
}

resources/views/maquinarias/create.blade.php
@extends('adminlte::page')

@section('title', 'Maquinaria')

@section('content_header')
    <h1>Maquinaria</h1>
@stop

@section('content')

    <p> REGISTRO DE PERSONAS.</p>

    <form action="/maquinarias" method="POST">
        @csrf
        <div class="container">
  <div class="row">
    <div class="mb-3 col">
    <label class="form-label">Nombre</label>
    <input name="nombre" id="nombre" type="text" class="form-control" wire:model="nombre">
    </div>
    <div class="mb-3 col">
    <label class="form-label">Codigo</label>
    <input name="codigo" id="codigo" type="text" class="form-control" wire:model="codigo">
    </div>
    <div class="mb-3 col">
    <label class="form-label">Modelo</label>
    <input name="modelo" id="modelo" type="text" class="form-control" wire:model="modelo">
    </div>
  </div>
  <div class="row">
  <div class="form-group col-md-3">
    <label class="form-label">Potencia</label>
    <input name="potencia" id="potencia" type="text" class="form-control" wire:model="potencia">
    </div>
    <div class="form-group col-md-3">
    <label class="form-label">Velocidad</label>
    <input name="velocidad" id="velocidad" type="text" class="form-control" wire:model="velocidad">
    </div>
    <div class="mb-3 col invisible">
        <label class="form-label">Estado</label>
        <input name="es_maquinaria" id="es_maquinaria" type="text" class="form-control" wire:model="es_maquinaria" value="1">
    </div>
    <div class="mb-3 col invisible">
        <label class="form-label">Estado</label>
        <input name="es_maquinaria1" id="es_maquinaria" type="text" class="form-control" wire:model="es_maquinaria" value="1">
    </div>
  </div>
  </div>
</div>
<div class="float-end">
            <a href="/maquinarias" class="me-2 btn btn-danger">Cerrar</a>
            <button  type="submit" class="btn btn-success">Guardar</button>
        </div>
    </form>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/maquinarias/edit.blade.php
@extends('adminlte::page')

@section('title', 'Maquinaria')

@section('content_header')
    <h1>Maquinaria</h1>
@stop

@section('content')

    <p> REGISTRO DE PERSONAS.</p>

    <form action="/maquinarias/{{$maquinarias->id}}" method="POST">
        @csrf
        @method('PUT')
        <div class="container">
        <div class="row">
    <div class="mb-3 col">
    <label class="form-label">Nombre</label>
    <input name="nombre" id="nombre" type="text" class="form-control" wire:model="nombre" value="{{$maquinarias->nombre}}">
    </div>
    <div class="mb-3 col">
    <label class="form-label">Codigo</label>
    <input name="codigo" id="codigo" type="text" class="form-control" wire:model="codigo" value="{{$maquinarias->codigo}}">
    </div>
    <div class="mb-3 col">
    <label class="form-label">Modelo</label>
    <input name="modelo" id="modelo" type="text" class="form-control" wire:model="modelo" value="{{$maquinarias->modelo}}">
    </div>
  </div>
  <div class="row">
  <div class="form-group col-md-3">
    <label class="form-label">Potencia</label>
    <input name="potencia" id="potencia" type="text" class="form-control" wire:model="potencia" value="{{$maquinarias->potencia}}">
    </div>
    <div class="form-group col-md-3">
    <label class="form-label">Velocidad</label>
    <input name="velocidad" id="velocidad" type="text" class="form-control" wire:model="velocidad" value="{{$maquinarias->velocidad}}">
    </div>
    <div class="mb-3 col invisible">
        <label class="form-label">Estado</label>
        <input name="es_maquinaria" id="es_maquinaria" type="text" class="form-control" wire:model="es_maquinaria" value="1" value="{{$maquinarias->es_maquinaria}}">
    </div>
  </div>
  </div>
</div>
<div class="float-end">
            <a href="/maquinarias" class="me-2 btn btn-danger">Cerrar</a>
            <button  type="submit" class="btn btn-success">Actaulizar</button>
        </div>
    </form>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/maquinarias/list.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')

    <p> REGISTRO DE PERSONAS.</p>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">DataTable with minimal features & hover style</h3>
                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <div class="input-group-append">
                    <a href="maquinarias/create" class="btn btn-success">Agregar Maquinaria</a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Nombres</th>
                    <th>Codigo</th>
                    <th>Modelo</th>
                    <th>Potencia</th>
                    <th>Velocidad</th>
                    <th>Acciones</th>
                  </tr>
                  </thead>
                  <tbody>
                      @foreach($maquinarias as $item)
                    <tr>
                      <td>{{$item->id}}</td>
                      <td>{{$item->nombre}}</td>
                      <td>{{$item->codigo}}</td>
                      <td>{{$item->modelo}}</td>
                      <td>{{$item->potencia}}</td>
                      <td>{{$item->velocidad}}</td>
                      <td>
                        <a class="btn btn-warning" href="/maquinarias/{{$item->id}}/edit">Editar</a>
                        <form action="{{route('maquinarias.destroy', $item->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit"  class="btn btn-danger">Eliminar</button>
                        </form>
                    </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <div class="card">
              <div class="card-header">
                <h3 class="card-title">DataTable with default features</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                  <th>ID</th>
                    <th>Nombres</th>
                    <th>Codigo</th>
                    <th>Modelo</th>
                    <th>Potencia</th>
                    <th>Velocidad</th>
                  </tr>
                  </thead>
                  <tbody>
                  @foreach($maquinarias as $item)
                    <tr>
                      <td>{{$item->id}}</td>
                      <td>{{$item->nombre}}</td>
                      <td>{{$item->codigo}}</td>
                      <td>{{$item->modelo}}</td>
                      <td>{{$item->potencia}}</td>
                      <td>{{$item->velocidad}}</td>
                    </tr>
                    @endforeach
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
@stop

@section('css')
    <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

@stop

@section('js')
    <script> console.log('Hi!'); </script>
<!-- DataTables  & Plugins -->
<script src="/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="/plugins/jszip/jszip.min.js"></script>
<script src="/plugins/pdfmake/pdfmake.min.js"></script>
<script src="/plugins/pdfmake/vfs_fonts.js"></script>
<script src="/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
@stop